/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.summercoding.bank.ui;

import com.summercoding.bank.controlleur.Controller;
import com.summercoding.bank.entities.Admin;
import com.summercoding.bank.entities.Compte;
import com.summercoding.bank.entities.Utilisateur;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edika Edmond Junior
 */
public class JFrameHome extends javax.swing.JFrame {

    //Controlleur
    Controller controller = new Controller();
    
    //Interface saveAdmin
    JFrameSaveAdmin saveAdminPage = new JFrameSaveAdmin();
    
    //Interface saveUtilisateur
    JFrameSaveUtilisateur saveUtilisateurPage = new JFrameSaveUtilisateur();
    
    //Interface saveCompte
    JFrameSaveCompte saveComptePage = new JFrameSaveCompte();
    
    /**
     * Creates new form JFrameHome
     */
    public JFrameHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListAdminOrUserOrCompte = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemCreerAdmin = new javax.swing.JMenuItem();
        menuItemListerAdmin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemCreeruser = new javax.swing.JMenuItem();
        menuItemListerUser = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        menuItemCreerCompte = new javax.swing.JMenuItem();
        menuItemListerCompte = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableListAdminOrUserOrCompte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableListAdminOrUserOrCompte);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Admin");

        menuItemCreerAdmin.setText("Créer");
        menuItemCreerAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreerAdminActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCreerAdmin);

        menuItemListerAdmin.setText("Lister");
        menuItemListerAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListerAdminActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemListerAdmin);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("User");

        menuItemCreeruser.setText("Créer");
        menuItemCreeruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreeruserActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemCreeruser);

        menuItemListerUser.setText("Lister");
        menuItemListerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListerUserActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemListerUser);

        jMenuBar1.add(jMenu2);

        jMenu9.setText("Compte");

        menuItemCreerCompte.setText("Créer");
        menuItemCreerCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreerCompteActionPerformed(evt);
            }
        });
        jMenu9.add(menuItemCreerCompte);

        menuItemListerCompte.setText("Lister");
        menuItemListerCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListerCompteActionPerformed(evt);
            }
        });
        jMenu9.add(menuItemListerCompte);

        jMenuBar1.add(jMenu9);

        jMenu3.setText("A propos");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Aide");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCreerAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreerAdminActionPerformed
        saveAdminPage.setVisible(true);
    }//GEN-LAST:event_menuItemCreerAdminActionPerformed

    private void menuItemListerAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListerAdminActionPerformed
        try {
            List<Admin> listAdmin = controller.routeVerslistAllAdmin();
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Id");
            model.addColumn("Nom");
            model.addColumn("Login");
            
            for(Admin admin : listAdmin){
                model.addRow(new String[]{admin.getIdAdmin()+"", admin.getNom(), admin.getLogin()});
            }
            
            tableListAdminOrUserOrCompte.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemListerAdminActionPerformed

    private void menuItemCreeruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreeruserActionPerformed
        saveUtilisateurPage.setVisible(true);
    }//GEN-LAST:event_menuItemCreeruserActionPerformed

    private void menuItemListerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListerUserActionPerformed
        try {
            List<Utilisateur> listUtilisateur = controller.routeVersAllUtilisateur();
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Id");
            model.addColumn("Nom");
            model.addColumn("Prenom");
            model.addColumn("Date de naissance");
            model.addColumn("Genre");
            model.addColumn("Login");
            model.addColumn("Password");
            model.addColumn("IdAdmin");
            
            for(Utilisateur utilisateur : listUtilisateur){
                model.addRow(new String[]{utilisateur.getIdUser()+"", utilisateur.getNom(), utilisateur.getPrenom(), utilisateur.getDateNaissance().toString(),utilisateur.getGenre(), utilisateur.getLogin(), utilisateur.getPassword(), utilisateur.getIdAdmin()+""});
            }
            
            tableListAdminOrUserOrCompte.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemListerUserActionPerformed

    private void menuItemCreerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreerCompteActionPerformed
        saveComptePage.setVisible(true);
    }//GEN-LAST:event_menuItemCreerCompteActionPerformed

    private void menuItemListerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListerCompteActionPerformed
        try {
            List<Compte> listCompte = controller.routeVersAllCompte();
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Id");
            model.addColumn("IdUser");
            model.addColumn("IdAdmin");
            model.addColumn("Solde");
            
            
            for(Compte compte : listCompte){
                model.addRow(new String[]{compte.getIdCompte()+"", compte.getIdUser()+"", compte.getIdAdmin()+"", compte.getSolde()+""});
            }
            
            tableListAdminOrUserOrCompte.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemListerCompteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuItemCreerAdmin;
    private javax.swing.JMenuItem menuItemCreerCompte;
    private javax.swing.JMenuItem menuItemCreeruser;
    private javax.swing.JMenuItem menuItemListerAdmin;
    private javax.swing.JMenuItem menuItemListerCompte;
    private javax.swing.JMenuItem menuItemListerUser;
    private javax.swing.JTable tableListAdminOrUserOrCompte;
    // End of variables declaration//GEN-END:variables
}
